<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class VacanteSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $vacantes = [
            [
                'titulo' => 'Ingeniero DevOps Senior',
                'salario_id' => 6,
                'categoria_id' => 7,
                'empresa' => 'CloudNova Systems',
                'ultimo_dia' => '2025-12-01',
                'descripcion' => 'Buscamos un Ingeniero DevOps Senior con experiencia en pipelines CI/CD, contenedores y automatización.',
                'imagen' => 'devops1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'QA Automation Engineer',
                'salario_id' => 3,
                'categoria_id' => 8,
                'empresa' => 'TestCore Labs',
                'ultimo_dia' => '2025-12-05',
                'descripcion' => 'Se requiere QA Automation Engineer con experiencia en pruebas funcionales y automatización con Selenium o Cypress.',
                'imagen' => 'qa_auto1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Arquitecto de Software',
                'salario_id' => 7,
                'categoria_id' => 6,
                'empresa' => 'Blueprint Technologies',
                'ultimo_dia' => '2025-12-10',
                'descripcion' => 'Se busca Arquitecto de Software para diseñar sistemas robustos y escalables.',
                'imagen' => 'arquitecto1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Desarrollador Full Stack Laravel + Vue',
                'salario_id' => 4,
                'categoria_id' => 3,
                'empresa' => 'StackForge Studio',
                'ultimo_dia' => '2025-12-02',
                'descripcion' => 'Buscamos Full Stack con experiencia en Laravel, Vue.js, APIs REST y MySQL.',
                'imagen' => 'fullstack1.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'Administrador de Bases de Datos',
                'salario_id' => 5,
                'categoria_id' => 12,
                'empresa' => 'DataGuard Solutions',
                'ultimo_dia' => '2025-12-03',
                'descripcion' => 'Se requiere DBA con experiencia en tuning, replicación y seguridad de datos.',
                'imagen' => 'dba1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Diseñador UX/UI Senior',
                'salario_id' => 4,
                'categoria_id' => 13,
                'empresa' => 'CreativeFlow Studio',
                'ultimo_dia' => '2025-12-12',
                'descripcion' => 'Buscamos diseñador UX/UI con dominio de Figma y diseño centrado en el usuario.',
                'imagen' => 'ux1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Ingeniero de Datos Junior',
                'salario_id' => 2,
                'categoria_id' => 9,
                'empresa' => 'DataStream Analytics',
                'ultimo_dia' => '2025-12-07',
                'descripcion' => 'Puesto de Ingeniero de Datos junior para procesos ETL y diseño de pipelines.',
                'imagen' => 'data_eng1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Científico de Datos con Python',
                'salario_id' => 7,
                'categoria_id' => 10,
                'empresa' => 'AI Metrics Corp',
                'ultimo_dia' => '2025-12-20',
                'descripcion' => 'Trabajo enfocado en machine learning, análisis estadístico y modelos predictivos.',
                'imagen' => 'ml1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Especialista en ciberseguridad ofensiva',
                'salario_id' => 7,
                'categoria_id' => 11,
                'empresa' => 'ShieldSec',
                'ultimo_dia' => '2025-12-18',
                'descripcion' => 'Se requiere especialista en pentesting, auditorías y pruebas de intrusión.',
                'imagen' => 'cyber1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Soporte Técnico Nivel 2',
                'salario_id' => 1,
                'categoria_id' => 14,
                'empresa' => 'HelpDesk Pro',
                'ultimo_dia' => '2025-12-15',
                'descripcion' => 'Puesto de soporte técnico para resolución de incidencias y mantenimiento básico.',
                'imagen' => 'support1.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'Líder Técnico Backend',
                'salario_id' => 6,
                'categoria_id' => 5,
                'empresa' => 'TechMasters',
                'ultimo_dia' => '2025-12-11',
                'descripcion' => 'Líder técnico para coordinar equipo de desarrollo backend.',
                'imagen' => 'lead1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Desarrollador Móvil Flutter',
                'salario_id' => 3,
                'categoria_id' => 4,
                'empresa' => 'AppWaves',
                'ultimo_dia' => '2025-12-14',
                'descripcion' => 'Flutter developer para aplicaciones multiplataforma.',
                'imagen' => 'flutter1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Backend Node.js Senior',
                'salario_id' => 7,
                'categoria_id' => 1,
                'empresa' => 'NodePrime Labs',
                'ultimo_dia' => '2025-12-22',
                'descripcion' => 'Experto en Node.js, microservicios y arquitecturas escalables.',
                'imagen' => 'node1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Frontend React Developer',
                'salario_id' => 4,
                'categoria_id' => 2,
                'empresa' => 'Reactify Studio',
                'ultimo_dia' => '2025-12-19',
                'descripcion' => 'React developer para desarrollo de interfaces modernas.',
                'imagen' => 'react1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Full Stack Python + React',
                'salario_id' => 4,
                'categoria_id' => 3,
                'empresa' => 'HybridStack',
                'ultimo_dia' => '2025-12-09',
                'descripcion' => 'Full stack developer para proyectos de analítica avanzada.',
                'imagen' => 'full2.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'DBA SQL Server Senior',
                'salario_id' => 6,
                'categoria_id' => 12,
                'empresa' => 'SecureData Corp',
                'ultimo_dia' => '2025-12-30',
                'descripcion' => 'DBA experto en SQL Server, AlwaysOn y tuning avanzado.',
                'imagen' => 'dba2.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Ingeniero DevOps AWS',
                'salario_id' => 5,
                'categoria_id' => 7,
                'empresa' => 'CloudStack MX',
                'ultimo_dia' => '2025-12-08',
                'descripcion' => 'DevOps con experiencia en AWS, Terraform y contenedores Docker.',
                'imagen' => 'aws_devops.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'QA Manual Tester',
                'salario_id' => 2,
                'categoria_id' => 8,
                'empresa' => 'QualitySoft',
                'ultimo_dia' => '2025-12-06',
                'descripcion' => 'QA manual con experiencia en pruebas funcionales y regresión.',
                'imagen' => 'qa2.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'Científico de Datos Junior',
                'salario_id' => 3,
                'categoria_id' => 10,
                'empresa' => 'InsightAI',
                'ultimo_dia' => '2025-12-16',
                'descripcion' => 'Jr Data Scientist para modelos básicos de machine learning.',
                'imagen' => 'ml2.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Frontend Angular Developer',
                'salario_id' => 3,
                'categoria_id' => 2,
                'empresa' => 'AngularPro',
                'ultimo_dia' => '2025-12-13',
                'descripcion' => 'Angular developer para desarrollo de paneles administrativos.',
                'imagen' => 'angular1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Soporte Técnico Nivel 1',
                'salario_id' => 1,
                'categoria_id' => 14,
                'empresa' => 'TechAssist',
                'ultimo_dia' => '2025-12-09',
                'descripcion' => 'Puesto de soporte técnico para atención a clientes.',
                'imagen' => 'support2.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'Product Manager Senior',
                'salario_id' => 7,
                'categoria_id' => 15,
                'empresa' => 'ProdTech',
                'ultimo_dia' => '2025-12-28',
                'descripcion' => 'PM para coordinar ciclo completo de producto digital.',
                'imagen' => 'pm1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Ingeniero de Datos Senior',
                'salario_id' => 7,
                'categoria_id' => 9,
                'empresa' => 'DataForge',
                'ultimo_dia' => '2025-12-27',
                'descripcion' => 'Senior Data Engineer con experiencia en Spark y Data Lakes.',
                'imagen' => 'data_eng2.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Especialista en Seguridad en la Nube',
                'salario_id' => 8,
                'categoria_id' => 11,
                'empresa' => 'CloudShield',
                'ultimo_dia' => '2025-12-21',
                'descripcion' => 'Especialista en ciberseguridad para entornos cloud.',
                'imagen' => 'cloud_sec1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Android Developer',
                'salario_id' => 3,
                'categoria_id' => 4,
                'empresa' => 'MobileCorp',
                'ultimo_dia' => '2025-12-17',
                'descripcion' => 'Developer Android para apps nativas Kotlin.',
                'imagen' => 'android1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'iOS Developer Swift',
                'salario_id' => 4,
                'categoria_id' => 4,
                'empresa' => 'SwiftWorks',
                'ultimo_dia' => '2025-12-22',
                'descripcion' => 'iOS Developer con experiencia en Swift y UIKit.',
                'imagen' => 'ios1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Data Analyst',
                'salario_id' => 3,
                'categoria_id' => 9,
                'empresa' => 'VisionData',
                'ultimo_dia' => '2025-12-23',
                'descripcion' => 'Data analyst con dominio de SQL y PowerBI.',
                'imagen' => 'data_an1.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'Diseñador UI Junior',
                'salario_id' => 2,
                'categoria_id' => 13,
                'empresa' => 'UXFlow',
                'ultimo_dia' => '2025-12-26',
                'descripcion' => 'Diseñador junior de interfaces.',
                'imagen' => 'ui_jr1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Backend PHP Developer',
                'salario_id' => 3,
                'categoria_id' => 1,
                'empresa' => 'CodeStack',
                'ultimo_dia' => '2025-12-11',
                'descripcion' => 'Backend con experiencia en PHP 8 y Laravel.',
                'imagen' => 'php1.png',
                'publicado' => 1,
                'user_id' => 4,
            ],
            [
                'titulo' => 'Frontend Svelte Developer',
                'salario_id' => 4,
                'categoria_id' => 2,
                'empresa' => 'SvelteHub',
                'ultimo_dia' => '2025-12-29',
                'descripcion' => 'Experiencia en Svelte y animaciones.',
                'imagen' => 'svelte1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Machine Learning Engineer',
                'salario_id' => 8,
                'categoria_id' => 10,
                'empresa' => 'NeuroAI',
                'ultimo_dia' => '2025-12-30',
                'descripcion' => 'ML Engineer con experiencia en TensorFlow y PyTorch.',
                'imagen' => 'ml3.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Soporte Técnico On-Site',
                'salario_id' => 1,
                'categoria_id' => 14,
                'empresa' => 'FixIt Tech',
                'ultimo_dia' => '2025-12-30',
                'descripcion' => 'Soporte en sitio para hardware y redes.',
                'imagen' => 'support3.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Líder Técnico Frontend',
                'salario_id' => 6,
                'categoria_id' => 5,
                'empresa' => 'LeadFront',
                'ultimo_dia' => '2025-12-13',
                'descripcion' => 'Liderazgo de equipo frontend.',
                'imagen' => 'lead_front.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Desarrollador Full Stack',
                'salario_id' => 3,
                'categoria_id' => 3,
                'empresa' => 'NextGen Labs',
                'ultimo_dia' => '2025-11-25',
                'descripcion' => 'Se busca Desarrollador Full Stack con experiencia en Laravel y Vue.js.',
                'imagen' => 'fullstack1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Desarrollador Móvil iOS',
                'salario_id' => 4,
                'categoria_id' => 4,
                'empresa' => 'AppHouse',
                'ultimo_dia' => '2025-11-27',
                'descripcion' => 'Buscamos Desarrollador Móvil especializado en iOS para apps innovadoras.',
                'imagen' => 'movil1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Líder Técnico Backend',
                'salario_id' => 5,
                'categoria_id' => 5,
                'empresa' => 'TechVision',
                'ultimo_dia' => '2025-11-30',
                'descripcion' => 'Líder Técnico con experiencia en sistemas escalables y equipos ágiles.',
                'imagen' => 'lider1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Arquitecto de Software',
                'salario_id' => 6,
                'categoria_id' => 6,
                'empresa' => 'SoftArchitects',
                'ultimo_dia' => '2025-12-05',
                'descripcion' => 'Arquitecto de Software con experiencia en diseño de microservicios y Cloud.',
                'imagen' => 'arquitecto1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Ingeniero DevOps',
                'salario_id' => 4,
                'categoria_id' => 7,
                'empresa' => 'CloudMasters',
                'ultimo_dia' => '2025-12-01',
                'descripcion' => 'Buscamos Ingeniero DevOps con experiencia en CI/CD y AWS.',
                'imagen' => 'devops1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'QA / Ingeniero de Pruebas',
                'salario_id' => 2,
                'categoria_id' => 8,
                'empresa' => 'QualitySoft',
                'ultimo_dia' => '2025-11-28',
                'descripcion' => 'Ingeniero QA con experiencia en pruebas automatizadas y manuales.',
                'imagen' => 'qa1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Ingeniero de Datos Junior',
                'salario_id' => 2,
                'categoria_id' => 9,
                'empresa' => 'DataAnalytics',
                'ultimo_dia' => '2025-12-03',
                'descripcion' => 'Buscamos Ingeniero de Datos Junior con ganas de crecer en proyectos de Big Data.',
                'imagen' => 'datos1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
            [
                'titulo' => 'Científico de Datos / Machine Learning',
                'salario_id' => 6,
                'categoria_id' => 10,
                'empresa' => 'AI Innovators',
                'ultimo_dia' => '2025-12-06',
                'descripcion' => 'Científico de Datos especializado en Machine Learning y análisis predictivo.',
                'imagen' => 'ml1.png',
                'publicado' => 1,
                'user_id' => 1,
            ],
            [
                'titulo' => 'Especialista en Ciberseguridad',
                'salario_id' => 5,
                'categoria_id' => 11,
                'empresa' => 'CyberSafe',
                'ultimo_dia' => '2025-12-04',
                'descripcion' => 'Se busca especialista en ciberseguridad para proteger infraestructuras críticas.',
                'imagen' => 'cyber1.png',
                'publicado' => 1,
                'user_id' => 2,
            ],
            [
                'titulo' => 'Administrador de Bases de Datos',
                'salario_id' => 4,
                'categoria_id' => 12,
                'empresa' => 'DB Experts',
                'ultimo_dia' => '2025-12-02',
                'descripcion' => 'Administrador DBA con experiencia en MySQL, PostgreSQL y MongoDB.',
                'imagen' => 'dba1.png',
                'publicado' => 1,
                'user_id' => 3,
            ],
        ];

        // Insertamos con timestamps
        foreach ($vacantes as &$v) {
            $v['created_at'] = $now;
            $v['updated_at'] = $now;
        }

        DB::table('vacantes')->insert($vacantes);
    }
}
